/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'VIVI OSPITIA' at '28/04/18 12:54 PM' with Gradle 2.14.1
 *
 * @author VIVI OSPITIA, @date 28/04/18 12:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
