import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'VIVI OSPITIA' at '28/04/18 12:54 PM' with Gradle 2.14.1
 *
 * @author VIVI OSPITIA, @date 28/04/18 12:54 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
